### PR TITLE
adding xfix style queries

### LINKED ISSUE #585: Full text search not working on tag fields
`id: str  = Field(index=True, full_text_search=True, primary_key=True)`

This fields creates schema as:
`ON JSON PREFIX 1 :index: SCHEMA $.id AS id TAG SEPARATOR | $.id AS id_fts TEXT`

Query:
`Model.id % id`

This doesn't work

### PR DESCRIPTION
**Pull request by slorello89**
Adding x-fix style queries. Should resolve #585

### CODE REVIEW

**Review by guyroyse — APPROVED** [review]
LGTM.

**Comment by Joybaruah** [comment]
Awesome!

**Comment by Joybaruah** [comment]
@slorello89 Hi, i think async code was merged to aredis_om.

**Comment by slorello89** [comment]
Yes, the sync code is generated (make sync)

**Comment by Joybaruah** [comment]
So, do we need to generate sync code after installing from pip?

**Comment by Joybaruah** [comment]
After installing redis_om 0.3.0 new changes in [feat/xfix-operations](https://github.com/redis/redis-om-python/tree/feat/xfix-operations) is missing from `redis_om/model/model.py`.

**Comment by slorello89** [comment]
Those updates will be coming in 0.3.1 - they have not been released yet

**Comment by Joybaruah** [comment]
Got it, thanks!

**Pull request merged**
