### PR TITLE
Fix full text search field indexing issue

### LINKED ISSUE #42: Index isn't created correctly when using full text search field?
I don't think the index is getting created correctly when using a full text search field... here a field `description_fts` is created in the index, but it doesn't say to use the field `description` as the field to search in... so I am unable to do any full text queries on `description`:

Model:

```python
from typing import Text
from redis_om import (Field, HashModel)

class Adoptable(HashModel):
    name: str = Field(index=True)
    species: str = Field(index=True)
    age: int = Field(index=True)
    weight: float = Field(index=True)
    sex: str = Field(index=True)
    fee: float = Field(index=True)
    children: str = Field(index=True)
    other_animals: str = Field(index=True)
    description: str = Field(index=True, full_text_search=True)
```

`FT.CREATE` Redis command generated when I run migrator as seen by Redis `MONITOR` command:

```
"ft.create" ":adoptable.Adoptable:index" "ON" "HASH" "PREFIX" "1" ":adoptable.Adoptable:" "SCHEMA" "pk" "TAG" "SEPARATOR" "|" "name" "TAG" "SEPARATOR" "|" "species" "TAG" "SEPARATOR" "|" "age" "NUMERIC" "weight" "NUMERIC" "sex" "TAG" "SEPARATOR" "|" "fee" "NUMERIC" "children" "TAG" "SEPARATOR" "|" "other_animals" "TAG" "SEPARATOR" "|" "description" "TAG" "SEPARATOR" "|" "description_fts" "TEXT"
```

Hashes created using `.save()` don't have a `description_fts` field so this doesn't appear to work.  Probably needs something like this in the index create command:

```
"description" "AS" "description_fts" "TEXT" 
```

I think the issue is here https://github.com/redis/redis-om-python/blob/3a3ed91ed03732789cca12b6ca3aed6cb5c5467b/aredis_om/model/model.py#L1432

which should likely say:

```
f"{name} AS {name}_fts TEXT "
```

### PR DESCRIPTION
**Pull request by simonprickett**
Adds field name alias to fix full text searches.   Tested with HashModel.

Closes #42

### CODE REVIEW

**Comment by abrookins** [comment]
This seems right, but you'll need to update the schema tests. I'm also curious why there aren't tests that failed without this working...

**Comment by simonprickett** [comment]
@abrookins good point about updating the tests, I'll give that a go and if successful will make a futher commit on this PR.

**Comment by simonprickett** [comment]
I've added a couple of tests, but sill see issues when running `make test` - example:

```
=========================== short test summary info ============================
FAILED tests/test_hash_model.py::test_schema - AssertionError: assert ('ON HA...
FAILED tests/test_json_model.py::test_recursive_query_field_resolution - Asse...
FAILED tests/test_json_model.py::test_exact_match_queries - AssertionError: a...
FAILED tests/test_json_model.py::test_tag_queries_boolean_logic - AssertionEr...
FAILED tests/test_json_model.py::test_recursive_query_expression_resolution
FAILED tests/test_json_model.py::test_in_query - AssertionError: assert [] ==...
FAILED tests/test_json_model.py::test_update_query - assert 0 == 3
FAILED tests/test_json_model.py::test_tag_queries_negation - AssertionError: ...
FAILED tests/test_json_model.py::test_tag_queries_punctuation - aredis_om.mod...
FAILED tests/test_json_model.py::test_list_field_limitations - AssertionError...
FAILED tests_sync/test_hash_model.py::test_schema - AssertionError: assert ('...
FAILED tests_sync/test_json_model.py::test_in_query - AssertionError: assert ...
FAILED tests_sync/test_json_model.py::test_update_query - assert 0 == 3
FAILED tests_sync/test_json_model.py::test_exact_match_queries - AssertionErr...
FAILED tests_sync/test_json_model.py::test_tag_queries_negation - AssertionEr...
FAILED tests_sync/test_json_model.py::test_tag_queries_boolean_logic - Assert...
FAILED tests_sync/test_json_model.py::test_recursive_query_expression_resolution
FAILED tests_sync/test_json_model.py::test_recursive_query_field_resolution
FAILED tests_sync/test_json_model.py::test_list_field_limitations - Assertion...
FAILED tests_sync/test_json_model.py::test_tag_queries_punctuation - redis_om...
FAILED tests_sync/test_oss_redis_features.py::test_all_keys - assert 1 == 3
======================== 21 failed, 101 passed in 3.89s ========================
```

The errors don't appear to be in the test I've added, I'll try running `make test` on the `main` branch and see what happens there.

**Comment by simonprickett** [comment]
> This seems right, but you'll need to update the schema tests. I'm also curious why there aren't tests that failed without this working...

Amended the schema tests and added a couple basic fuzzy queries for the hash model too.

**Comment by simonprickett** [comment]
Test results after latest commit (I see same on main):

```
$ make test
...
FAILED tests/test_json_model.py::test_update_query - assert 0 == 3
FAILED tests/test_json_model.py::test_in_query - AssertionError: assert [] == [Member(pk='01FRP...
FAILED tests/test_json_model.py::test_tag_queries_boolean_logic - AssertionError: assert [] == ...
FAILED tests/test_json_model.py::test_recursive_query_expression_resolution - AssertionError: a...
FAILED tests/test_json_model.py::test_exact_match_queries - AssertionError: assert [] == [Membe...
FAILED tests/test_json_model.py::test_tag_queries_negation - AssertionError: assert [Member(pk=...
FAILED tests/test_json_model.py::test_recursive_query_field_resolution - AssertionError: assert...
FAILED tests/test_json_model.py::test_tag_queries_punctuation - aredis_om.model.model.NotFoundE...
FAILED tests/test_json_model.py::test_list_field_limitations - AssertionError: assert [] == [Ta...
FAILED tests_sync/test_json_model.py::test_exact_match_queries - AssertionError: assert [] == [...
FAILED tests_sync/test_json_model.py::test_update_query - assert 0 == 3
FAILED tests_sync/test_json_model.py::test_in_query - AssertionError: assert [] == [Member(pk='...
FAILED tests_sync/test_json_model.py::test_tag_queries_boolean_logic - AssertionError: assert [...
FAILED tests_sync/test_json_model.py::test_recursive_query_expression_resolution - AssertionErr...
FAILED tests_sync/test_json_model.py::test_recursive_query_field_resolution - AssertionError: a...
FAILED tests_sync/test_json_model.py::test_tag_queries_negation - AssertionError: assert [Membe...
FAILED tests_sync/test_json_model.py::test_tag_queries_punctuation - redis_om.model.model.NotFo...
FAILED tests_sync/test_json_model.py::test_list_field_limitations - AssertionError: assert [] =...
================================= 18 failed, 104 passed in 4.49s =================================
make: *** [Makefile:66: test] Error 1
```

**Comment by simonprickett** [comment]
I've double checked this against the versions of RediSearch/RedisJSON currently on Redis Enterprise cloud and it's working there too.

**Pull request merged**
